export function defaultBoosts() {
    return {

        // weapon cards
        wcdamage: 10.0,
        wcdamagen: false,
        wcdamager: 0.0,

        bloody_mess: {
            name: "Bloody Mess",
            value: 5.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [5.0, 10.0, 15.0],
            x: 1,
            max_x: 1,
        },

        adrenaline: {
            name: "Adrenaline",
            value: 6.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [6.0, 7.0, 8.0, 9.0, 10.0],
            x: 1,
            max_x: 6,
        },

        toft: {
            name: "TOFT",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 20.0, 30.0, 40.0],
            x: 1,
            max_x: 1,
        },

        tenderizer: {
            name: "Tenderizer",
            value: 5.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [5.0, 7.0, 10.0],
            x: 1,
            max_x: 4,
        },

        glow_sight: {
            name: "Glow Sight",
            value: 20.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [20.0, 40.0, 60.0],
            x: 1,
            max_x: 1,
        },

        gun_foo: {
            name: "Gun Foo",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 30.0, 60.0],
            x: 1,
            max_x: 1,
        },

        syringer: {
            name: "Syringer",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0],
            x: 1,
            max_x: 1,
        },

        incisor: {
            name: "Incisor",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0, 50.0, 75.0],
            x: 1,
            max_x: 1,
        },

        bow_before_me: {
            name: "Bow Before Me",
            value: 12.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [12.0, 24.0, 36.0],
            x: 1,
            max_x: 1,
        },

        exterminator: {
            name: "Exterminator",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0, 50.0, 75.0],
            x: 1,
            max_x: 1,
        },

        tank_killer: {
            name: "Tank Killer",
            value: 12.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [12.0, 24.0, 36.0],
            x: 1,
            max_x: 1,
        },

        stabilized: {
            name: "Stabilized",
            value: 15.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [15.0, 30.0, 45.0],
            x: 1,
            max_x: 1,
        },

        covert_operative: {
            name: "Covert Operative",
            value: 2.15,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [2.15, 2.3, 2.5],
            x: 1,
            max_x: 1,
        },

        mister_sandman: {
            name: "Mister Sandman",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0, 50.0],
            x: 1,
            max_x: 1,
        },

        ninja: {
            name: "Ninja",
            value: 30.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [30.0, 60.0, 90.0],
            x: 1,
            max_x: 1,
        },

        follow_through: {
            name: "Follow Through",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 20.0, 30.0, 40.0],
            x: 1,
            max_x: 1,
        },

        demolition_expert: {
            name: "Demolition Expert",
            value: 20.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [20.0, 30.0, 40.0, 50.0, 60.0],
            x: 1,
            max_x: 1,
        },

        science: {
            name: "Science",
            value: 5.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [5.0, 10.0, 15.0, 20.0, 25.0, 30.0],
            x: 1,
            max_x: 1,
        },

        better_criticals: {
            name: "Better Criticals",
            value: 50.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [50.0, 75.0, 100.0],
            x: 1,
            max_x: 1,
        },

        nerd_rage: {
            name: "Nerd Rage",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20.0],
            x: 1,
            max_x: 1,
        },

        lock_and_load: {
            name: "Lock And Load",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
        },

        martial_artist: {
            name: "Martial Artist",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
        },

        scattershot: {
            name: "Scattershot",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
        },

        ground_pounder: {
            name: "Ground Pounder",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
        },

        party_girl_boy: {
            name: "Party Girl / Boy",
            value: 2.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [2, 3],
            x: 1,
            max_x: 1,
        },

        power_user: {
            name: "Power User",
            value: 130,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [130, 160, 200],
            x: 1,
            max_x: 1,
        },
        strange_in_numbers: {
            name: "Strange In Nums",
            value: 25,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25],
            x: 1,
            max_x: 1,
        },
        class_freak: {
            name: "Class Freak",
            value: 25,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25, 50, 75],
            x: 1,
            max_x: 1,
        },
    };
}