export function defaultBoosts() {
    return {
        bloody_mess: {
            name: "Bloody Mess",
            value: 5.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [5.0, 10.0, 15.0],
            x: 1,
            max_x: 1,
            category: "Luck",
            info: "{1}% bonus damage means enemies may explode into a gory red paste.",
            cost: [1, 2, 3],
        },

        adrenaline: {
            name: "Adrenaline",
            value: 6.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [6.0, 7.0, 8.0, 9.0, 10.0],
            x: 1,
            max_x: 6,
            category: "Agility",
            info: "Gain {1}% damage for 30s per kill. Duration refreshes with kills.",
            cost: [1, 2, 3, 4, 5],
        },

        toft: {
            name: "TOFT",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 20.0, 30.0, 40.0],
            x: 1,
            max_x: 1,
            category: "Legendary",
            info: "Enemies take {1}% more damage when they attack you, if you're on a team.",
            cost: [1, 2, 3, 4],
        },

        tenderizer: {
            name: "Tenderizer",
            value: 5.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [5.0, 7.0, 10.0],
            x: 1,
            max_x: 4,
            category: "Charisma",
            info: "Make your target receive {1}% more damage for {1} seconds after you attack.",
            cost: [1, 2, 3],
        },

        glow_sight: {
            name: "Glow Sight",
            value: 20.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [20.0, 40.0, 60.0],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 3],
            info: "Deal +{1}% damage to glowing enemies.",
        },

        gun_fu: {
            name: "Gun Fu",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 30.0, 60.0],
            x: 1,
            max_x: 1,
            category: "Agility",
            cost: [1, 2, 3],
            info: "V.A.T.S. swaps targets on kill with +{1}% damage to your next target.",
        },

        incisor: {
            name: "Incisor",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0, 50.0, 75.0],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 3],
            info: "Your melee weapons ignore {1}% of your target's armor.",
        },

        bow_before_me: {
            name: "Bow Before Me",
            value: 12.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [12.0, 24.0, 36.0],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 3],
            info: "Your bows and crossbows ignore {1}% armor and have a {2}% chance to stagger.",
        },

        exterminator: {
            name: "Exterminator",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0, 50.0, 75.0],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 3],
            info: "Your attacks ignore {1}% armor of any insect.",
        },

        tank_killer: {
            name: "Tank Killer",
            value: 12.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [12.0, 24.0, 36.0],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 3],
            info: "Your rifles and pistols ignore {1}% armor and have a {2}% chance to stagger.",
        },

        stabilized: {
            name: "Stabilized",
            value: 15.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [15.0, 30.0, 45.0],
            x: 1,
            max_x: 1,
            category: "Intelligence",
            cost: [1, 2, 3],
            info: "In Power Armor, heavy guns gain more accuracy and ignore {1}% armor.",
        },

        covert_operative: {
            name: "Covert Operative",
            value: 2.15,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [2.15, 2.3, 2.5],
            x: 1,
            max_x: 1,
            category: "Agility",
            cost: [1, 2, 3],
            info: "Your ranged sneak attacks do {1}x normal damage.",
        },

        mister_sandman: {
            name: "Mister Sandman",
            value: 25.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25.0, 50.0],
            x: 1,
            max_x: 1,
            category: "Agility",
            cost: [1, 2],
            info: "At night your silenced weapons do an additional {1}% sneak attack damage.",
        },

        ninja: {
            name: "Ninja",
            value: 30.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [30.0, 60.0, 90.0],
            x: 1,
            max_x: 1,
            category: "Agility",
            cost: [1, 2, 3],
            info: "Sneak attacks with melee weapons do an additional {1}% sneak attack damage.",
        },

        follow_through: {
            name: "Follow Through",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 20.0, 30.0, 40.0],
            x: 1,
            max_x: 1,
            category: "Legendary",
            cost: [1, 2, 3, 4],
            info: "Ranged sneak damage increases damage to target by {1}% for 10 seconds.",
        },

        demolition_expert: {
            name: "Demolition Expert",
            value: 20.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [20.0, 30.0, 40.0, 50.0, 60.0],
            x: 1,
            max_x: 1,
            category: "Intelligence",
            cost: [1, 2, 3, 4, 5],
            info: "Your explosives do +{1}% damage",
        },

        science: {
            name: "Science",
            value: 5.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [5.0, 10.0, 15.0, 20.0, 25.0, 30.0],
            x: 1,
            max_x: 1,
            category: "Intelligence",
            cost: [1, 2, 3, 4, 5, 6],
            info: "Energy damage gains +{1}% bonus.",
        },

        better_criticals: {
            name: "Better Criticals",
            value: 50.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [50.0, 75.0, 100.0],
            x: 1,
            max_x: 1,
            category: "Luck",
            cost: [1, 2, 3],
            info: "V.A.T.S. criticals now do +{1}% damage.",
        },

        nerd_rage: {
            name: "Nerd Rage",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10.0, 15.0, 20.0],
            x: 1,
            max_x: 1,
            category: "Intelligence",
            cost: [1, 2, 3],
            info: "While below 20% Health, gain {3} Damage Resist, {1}% damage and 15% AP regen.",
        },

        lock_and_load: {
            name: "Lock And Load",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 3],
            info: "Heavy guns reload +{1}% faster.",
        },

        martial_artist: {
            name: "Martial Artist",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 3],
            info: "Your melee weapons weight {3}% less, and you can swing them {1}% faster.",
        },

        scattershot: {
            name: "Scattershot",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 3],
            info: "Shotguns now weight {4}% less and you reload them {1}% faster.",
        },

        ground_pounder: {
            name: "Ground Pounder",
            value: 10.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 20, 30],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 3],
            info: "Automatic rifles now reload {1}% faster and have better hip fire accuracy.",
        },

        party_girl_boy: {
            name: "Party Girl / Boy",
            value: 2.0,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [2, 3],
            x: 1,
            max_x: 1,
            category: "Charisma",
            cost: [2, 3],
            info: "The effects of alcohol are {1}x.",
        },

        power_user: {
            name: "Power User",
            value: 130,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [130, 160, 200],
            x: 1,
            max_x: 1,
            category: "Intelligence",
            cost: [1, 2, 3],
            info: "Fusion Cores now last {1}% longer.",
        },

        strange_in_numbers: {
            name: "Strange In Nums",
            value: 25,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25],
            x: 1,
            max_x: 1,
            category: "Charisma",
            cost: [1],
            info: "Positive mutation effects are {1}% stronger if teammates are mutated too.",
        },

        class_freak: {
            name: "Class Freak",
            value: 25,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [25, 50, 75],
            x: 1,
            max_x: 1,
            category: "Luck",
            cost: [1, 2, 3],
            info: "The negative effects of your mutations are reduced by {1}%.",
        },

        gladiator: {
            name: "Gladiator",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your one-handed melee weapons now do +{1}% damage.",
        },

        heavy_gunner: {
            name: "Heavy Gunner",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your non-explosive heavy guns now do +{1}% damage.",
        },

        shotgunner: {
            name: "Shotgunner",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your shotguns now do +{1}% damage.",
        },

        slugger: {
            name: "Slugger",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your two-handed melee weapons now do +{1}% damage.",
        },

        iron_fist: {
            name: "Iron Fist",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20],
            x: 1,
            max_x: 1,
            category: "Strength",
            cost: [1, 2, 3],
            info: "Your punching attacks now do +{1}% damage.",
        },

        archer: {
            name: "Archer",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your bows and crossbows now do +{1}% damage.",
        },

        commando: {
            name: "Commando",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Basic combat training means automatic rifles do +{1}% damage.",
        },

        rifleman: {
            name: "Rifleman",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Perception",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your non-automatic rifles now do +{1}% damage.",
        },

        guerrilla: {
            name: "Guerrilla",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Agility",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your automatic pistols now do +{1}% damage",
        },

        gunslinger: {
            name: "Gunslinger",
            value: 10,
            is_used: false,
            displayed_value: 0.0,
            rank: 1,
            rank_values: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60],
            x: 1,
            max_x: 1,
            category: "Agility",
            cost: [1, 2, 2, 3, 3, 4, 5, 6, 7, 8, 9],
            info: "Your non-automatic pistols now do +{1}% damage.",
        },

        special: {
            strength: 0,
            perception: 0,
            endurance: 0,
            charisma: 0,
            intelligence: 0,
            agility: 0,
            luck: 0,
        }
    };
}