export function defaultCreatures() {
    return {
        creature: {
            name: "Creature",
            b: 10.0,
            e: 10.0,
            f: 10.0,
            p: 10.0,
            c: 10.0,
            r: 10.0,
            h: 100,
            damageToCreature: false,
            damageReduction: 0.0,
            headShot: 2.0,
            shotDamage: 0.0,
            normalDamage: 0.0,
            critNormalDamage: 0.0,
            explosiveDamage: 0.0,
            critExplosiveDamage: 0.0,
            dps: 0.0,
            ammo: 0.0,
            reloads: 0.0,
            reloadsTime: 0.0,
            lifeTime: 0.0,
            level: 1,
        },

        sbq: {
            name: "SB Queen",
            b: 300.0,
            e: 300.0,
            f: 300.0,
            p: 300.0,
            c: 300.0,
            r: Infinity,
            h: 32767,
            damageToCreature: false,
            damageReduction: 0.7,
            headShot: 1.5,
            shotDamage: 0.0,
            normalDamage: 0.0,
            critNormalDamage: 0.0,
            explosiveDamage: 0.0,
            critExplosiveDamage: 0.0,
            dps: 0.0,
            ammo: 0.0,
            reloads: 0.0,
            reloadsTime: 0.0,
            lifeTime: 0.0,
            level: "Max",
        },

        earle: {
            name: "Earle",
            b: 400.0,
            e: 400.0,
            f: 400.0,
            p: 400.0,
            c: 400.0,
            r: Infinity,
            h: 30000,
            damageToCreature: false,
            damageReduction: 0.8,
            headShot: 2.0,
            shotDamage: 0.0,
            normalDamage: 0.0,
            critNormalDamage: 0.0,
            explosiveDamage: 0.0,
            critExplosiveDamage: 0.0,
            dps: 0.0,
            ammo: 0.0,
            reloads: 0.0,
            reloadsTime: 0.0,
            lifeTime: 0.0,
            level: "Max",
        },

        titan: {
            name: "U Titan",
            b: 400.0,
            e: 400.0,
            f: 350.0,
            p: 400.0,
            c: 400.0,
            r: Infinity,
            h: 31000,
            damageToCreature: false,
            damageReduction: 0.7,
            headShot: 1.3,
            shotDamage: 0.0,
            normalDamage: 0.0,
            critNormalDamage: 0.0,
            explosiveDamage: 0.0,
            critExplosiveDamage: 0.0,
            dps: 0.0,
            ammo: 0.0,
            reloads: 0.0,
            reloadsTime: 0.0,
            lifeTime: 0.0,
            level: "Max",
        }
    };
}